const mongoose = require("mongoose");

let Schema = mongoose.Schema;

const passportLocalMongoose = require("passport-local-mongoose");

const userSchema = new Schema({
    email:{
        type:String ,
        required : true ,
    }
})

//so we are using here passport so username and password keys
//will be automatically generated by passport and will salted as well as hashed.

userSchema.plugin(passportLocalMongoose);
module.exports = mongoose.model('User', userSchema);
